import os

dirname = os.path.dirname(__file__)

bg_dict = {'Baby blue': dirname + '/images/Bg/Baby Blue.png',
'Green': dirname + '/images/Bg/Green.png',
'Grey blue': dirname + '/images/Bg/Grey Blue.png',
'Lavender': dirname + '/images/Bg/Lavender.png',
'Orange': dirname + '/images/Bg/orange.png',
'Red brown': dirname + '/images/Bg/Red Brown.png', 
'Yellow': dirname + '/images/Bg/yellow.png'}

type_dict = {'Alien': dirname + '/images/Type/alien.png',
'Ape': dirname + '/images/Type/ape.png',
'Female': dirname + '/images/Type/female.png',
'Male': dirname + '/images/Type/male.png',
'Zombie': dirname + '/images/Type/zombie.png'}

mouth_dict = {'Mask': dirname + '/images/Mouth/mask.png',
'Sad': dirname + '/images/Mouth/mouth 1.png',
'Flat': dirname + '/images/Mouth/mouth 2.png',
'Happy': dirname + '/images/Mouth/mouth 3.png'}

fmouth_dict = {
'fFlat': dirname + '/images/fMouth/mouth 2.png',
'fHappy': dirname + '/images/fMouth/mouth 3.png'}

eyes_dict = {'3d glasses': dirname + '/images/Eyes/3d glasses.png',
'Big sunglasses': dirname + '/images/Eyes/Big Sunglasses.png',
'Blue eyes': dirname + '/images/Eyes/blue eyes.png',
'Eye patch': dirname + '/images/Eyes/eyepatch.png',
'Glasses': dirname + '/images/Eyes/glasses.png',
'Mask': dirname + '/images/Eyes/mask.png',
'Nerd glasses': dirname + '/images/Eyes/nerd glasses.png',
'Small glasses': dirname + '/images/Eyes/small glasses.png',
'Sun glasses': dirname + '/images/Eyes/Sunglasses.png',
'VR': dirname + '/images/Eyes/vr.png',
'Welding goggles': dirname + '/images/Eyes/welding goggs.png',
'zNone': dirname + '/images/Eyes/znone.png'}

feyes_dict = {'3d glasses': dirname + '/images/Feyes/3d glasses.png',
'fBig sunglasses': dirname + '/images/Feyes/Big Sunglasses.png',
'fBlue eyes': dirname + '/images/Feyes/blue eyes.png',
'fBlue mascara': dirname + '/images/Feyes/blue mascara.png',
'fEye patch': dirname + '/images/Feyes/eyepatch.png',
'fGlasses': dirname + '/images/Feyes/glasses.png',
'fGreen mascara': dirname + '/images/Feyes/green mascara.png',
'fNerd glasses': dirname + '/images/Feyes/nerd glasses.png',
'fSmall glasses': dirname + '/images/Feyes/small glasses.png',
'fSun glasses': dirname + '/images/Feyes/Sunglasses.png',
'fVR': dirname + '/images/Feyes/vr.png',
'fWelding goggles': dirname + '/images/Feyes/welding goggs.png',
'fzNone': dirname + '/images/Feyes/znone.png'}

beard_dict = {'Beard': dirname + '/images/Beard/beard.png',
'Big beard': dirname + '/images/Beard/big beard.png',
'Bushy beard': dirname + '/images/Beard/bushy beard.png',
'Go-T': dirname + '/images/Beard/got.png',
'Handle-bar mustache': dirname + '/images/Beard/handlebar.png',
'Mutton-chops': dirname + '/images/Beard/muttonchops.png',
'zNone': dirname + '/images/Beard/znone.png'}


acc_dict = {
'Chain': dirname + '/images/Acc/chain.png',
'Cig': dirname + '/images/Acc/cig.png',
'Clown nose': dirname + '/images/Acc/clown nose.png',
'Earring': dirname + '/images/Acc/earring.png',
'Pipe': dirname + '/images/Acc/pipe.png',
'Vape': dirname + '/images/Acc/vape.png',
'zNone': dirname + '/images/Acc/znone.png'}

facc_dict = {'Chain': dirname + '/images/Facc/chain.png',
'fCig': dirname + '/images/Facc/cig.png',
'fClown nose': dirname + '/images/Facc/clown nose.png',
'fEarring': dirname + '/images/Facc/earring.png',
'fPipe': dirname + '/images/Facc/pipe.png',
'fVape': dirname + '/images/Facc/vape.png',
'fzNone': dirname + '/images/Facc/znone.png'}

head_dict = {'Bandana': dirname + '/images/Head/bandana.png',
'Beanie 1': dirname + '/images/Head/beanie.png',
'Beanie 2': dirname + '/images/Head/beaniee.png',
'Cap': dirname + '/images/Head/cap.png',
'Crazy hair': dirname + '/images/Head/crazy hair.png',
'Fedora': dirname + '/images/Head/fedora.png',
'Front hat': dirname + '/images/Head/front hat.png',
'Head band': dirname + '/images/Head/headband.png',
'Hood': dirname + '/images/Head/hood.png',
'Hat': dirname + '/images/Head/idkhat.png',
'Mohawk 2': dirname + '/images/Head/mohawk 2.png',
'Mohawk': dirname + '/images/Head/mohawk.png',
'Orange hair': dirname + '/images/Head/orange hair.png',
'Police hat': dirname + '/images/Head/police hat.png',
'Spiky hair': dirname + '/images/Head/spiky hair.png',
'Top hat': dirname + '/images/Head/tophat.png',
'zNone': dirname + '/images/Head/znone.png'}

fhead_dict = {'Bandana': dirname + '/images/Fhead/fbandana.png',
'fBeanie 1': dirname + '/images/Fhead/fbeanie.png',
'fBeanie 2': dirname + '/images/Fhead/fbeaniee.png',
'fBlonde 1': dirname + '/images/Fhead/fblonde 1.png',
'fBlonde 2': dirname + '/images/Fhead/fblonde 2.png',
'fCap': dirname + '/images/Fhead/fcap.png',
'fFedora': dirname + '/images/Fhead/ffedora.png',
'fFront hat': dirname + '/images/Fhead/ffront hat.png',
'fHead band': dirname + '/images/Fhead/fheadband.png',
'fHood': dirname + '/images/Fhead/fhood.png',
'fHat': dirname + '/images/Fhead/fidkhat.png',
'fMohawk 2': dirname + '/images/Fhead/fmohawk 2.png',
'fMohawk': dirname + '/images/Fhead/fmohawk.png',
'fOrange hair': dirname + '/images/Fhead/forange hair.png',
'fPilot hat': dirname + '/images/Fhead/fpilot hat.png',
'fPink pilot hat': dirname + '/images/Fhead/fpink pilot hat.png',
'fPolice hat': dirname + '/images/Fhead/fpolice har.png',
'fTiara': dirname + '/images/Fhead/ftiara.png',
'fTop hat': dirname + '/images/Fhead/ftophat.png',
'fzNone': dirname + '/images/Fhead/znone.png'}

psych_dict = {'1': dirname +'/images/Psychadelic/1.png',
'2': dirname +'/images/Psychadelic/2.png',
'3': dirname +'/images/Psychadelic/3.png',
'4': dirname +'/images/Psychadelic/4.png',
'5': dirname +'/images/Psychadelic/5.png',
'6': dirname +'/images/Psychadelic/6.png',
'7': dirname +'/images/Psychadelic/7.png',
'8': dirname +'/images/Psychadelic/8.png',
'9': dirname +'/images/Psychadelic/9.png',
'10': dirname +'/images/Psychadelic/10.png',
'11': dirname +'/images/Psychadelic/11.png',
'12': dirname +'/images/Psychadelic/12.png',
'13': dirname +'/images/Psychadelic/13.png',
'14': dirname +'/images/Psychadelic/14.png',
'15': dirname +'/images/Psychadelic/15.png',
'16': dirname +'/images/Psychadelic/16.png',
'17': dirname +'/images/Psychadelic/17.png',
'18': dirname +'/images/Psychadelic/18.png',
'19': dirname +'/images/Psychadelic/19.png',
'20': dirname +'/images/Psychadelic/20.png',
'21': dirname +'/images/Psychadelic/21.png',
'22': dirname +'/images/Psychadelic/22.png',
'23': dirname +'/images/Psychadelic/23.png',
'24': dirname +'/images/Psychadelic/24.png',
'25': dirname +'/images/Psychadelic/25.png',
'26': dirname +'/images/Psychadelic/26.png',
'27': dirname +'/images/Psychadelic/27.png',
'28': dirname +'/images/Psychadelic/28.png',
'29': dirname +'/images/Psychadelic/29.png',
'30': dirname +'/images/Psychadelic/30.png',
'31': dirname +'/images/Psychadelic/31.png',
'32': dirname +'/images/Psychadelic/32.png',
'33': dirname +'/images/Psychadelic/33.png',
'34': dirname +'/images/Psychadelic/34.png',
'35': dirname +'/images/Psychadelic/35.png',
'36': dirname +'/images/Psychadelic/36.png',
'37': dirname +'/images/Psychadelic/37.png',
'38': dirname +'/images/Psychadelic/38.png',
'39': dirname +'/images/Psychadelic/39.png',
'40': dirname +'/images/Psychadelic/40.png',
'41': dirname +'/images/Psychadelic/41.png',
'42': dirname +'/images/Psychadelic/41.png',
'43': dirname +'/images/Psychadelic/41.png',
'44': dirname +'/images/Psychadelic/41.png',
'45': dirname +'/images/Psychadelic/41.png',
'46': dirname +'/images/Psychadelic/41.png',
'47': dirname +'/images/Psychadelic/41.png',
'48': dirname +'/images/Psychadelic/41.png',
'49': dirname +'/images/Psychadelic/41.png',
'50': dirname +'/images/Psychadelic/41.png',
'51': dirname +'/images/Psychadelic/41.png'}
